import { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import LiveCoachFeed from "./LiveCoachFeed";
import { Radio, ChevronDown } from "lucide-react";

export default function LiveCoachPanel() {
  const [sessions, setSessions] = useState([]);
  const [selectedId, setSelectedId] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      const user = await base44.auth.me();
      // Load recent live sessions (last 7 days) — these are what the desktop app writes to
      const sevenDaysAgo = new Date();
      sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
      const recentDate = sevenDaysAgo.toISOString().split("T")[0];

      const [liveSessions, desktopSessions] = await Promise.all([
        base44.entities.LiveSession.filter({ owner_email: user.email }, "-stream_date", 10),
        base44.entities.DesktopSession.filter({ user_id: user.email }, "-started_at", 10),
      ]);

      // Build combined list for the selector
      const combined = [
        ...liveSessions.filter(s => s.stream_date >= recentDate).map(s => ({
          id: s.id,
          label: `${s.stream_date} · ${s.game}`,
          type: "live",
        })),
        ...desktopSessions.filter(s => s.started_at >= recentDate + "T00:00:00Z").map(s => ({
          id: s.session_id || s.id,
          label: `${(s.started_at || "").slice(0, 10)} · ${s.game || "Desktop"}`,
          type: "desktop",
        })),
      ];

      setSessions(combined);
      if (combined.length > 0) setSelectedId(combined[0].id);
      setLoading(false);
    }
    load();
  }, []);

  return (
    <div className="bg-[#060d1f] border border-pink-900/30 rounded-xl overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-white/5">
        <div className="flex items-center gap-2.5">
          <div className="relative">
            <Radio className="w-4 h-4 text-pink-400" />
            <span className="absolute -top-0.5 -right-0.5 w-1.5 h-1.5 bg-pink-500 rounded-full animate-pulse" />
          </div>
          <div>
            <p className="text-[10px] font-mono uppercase tracking-widest text-pink-400/60">Live Coach</p>
            <p className="text-sm font-black uppercase text-white">Real-Time Prompts</p>
          </div>
        </div>

        {/* Session selector */}
        {!loading && sessions.length > 0 && (
          <div className="relative">
            <select
              value={selectedId}
              onChange={e => setSelectedId(e.target.value)}
              className="appearance-none bg-[#02040f] border border-cyan-900/40 text-slate-400 text-xs font-mono rounded px-3 py-2 pr-7 outline-none focus:border-cyan-500/40 cursor-pointer"
            >
              {sessions.map(s => (
                <option key={s.id} value={s.id}>{s.label}</option>
              ))}
            </select>
            <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-slate-600 pointer-events-none" />
          </div>
        )}
      </div>

      {/* Feed */}
      <div className="p-4 min-h-[180px]">
        {loading ? (
          <div className="flex items-center justify-center py-10 gap-2">
            <div className="w-4 h-4 border-2 border-cyan-900 border-t-cyan-400 rounded-full animate-spin" />
          </div>
        ) : (
          <LiveCoachFeed sessionId={selectedId} />
        )}
      </div>

      {/* Footer note */}
      <div className="px-5 py-3 border-t border-white/5 bg-[#02040f]/40">
        <p className="text-[10px] font-mono text-slate-700 uppercase tracking-widest">
          Prompts are generated by the live state engine · Updates in real-time
        </p>
      </div>
    </div>
  );
}