import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

const SEED_GAMES = [
  {
    title: "Fortnite", slug: "fortnite", description_short: "Battle royale and creative sandbox with building mechanics.", developer: "Epic Games", publisher: "Epic Games", franchise: "Fortnite", multiplayer_type: "battle_royale", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "third_person", genres: ["Battle Royale", "Shooter", "Sandbox"], tags: ["building", "pvp", "team_based", "battle_royale", "creative"], game_modes: ["battle_royale", "creative", "ranked", "zero_build", "custom_match"], core_objective: "Be the last player or team standing by eliminating opponents and surviving the shrinking storm circle.", win_conditions: "Achieve Victory Royale by being the last alive. In ranked, gain rank points by placing high and getting eliminations.", fail_conditions: "Eliminated by another player, caught in storm, or entire squad wiped.", challenge_notes: "Building adds unique challenge dimensions. Zero Build mode is simpler for restriction challenges. Creative mode allows custom challenge maps.", safety_notes: "Cartoon violence, suitable for all audiences. No gore.", sort_priority: 1
  },
  {
    title: "Call of Duty: Warzone", slug: "warzone", description_short: "Free-to-play battle royale set in the Call of Duty universe.", developer: "Infinity Ward / Raven Software", publisher: "Activision", franchise: "Call of Duty", multiplayer_type: "battle_royale", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "first_person", genres: ["Battle Royale", "FPS", "Shooter"], tags: ["pvp", "team_based", "battle_royale", "tactical"], game_modes: ["battle_royale", "ranked", "resurgence", "plunder"], core_objective: "Survive and be the last squad standing in a large-scale battle royale map.", win_conditions: "Win the match by being the last team alive, or earn the most cash in Plunder.", fail_conditions: "Squad fully eliminated with no Gulag or buy-back available.", challenge_notes: "Loadout restrictions, pistol-only runs, and Gulag-focused challenges work great. Resurgence mode is good for faster challenge cycles.", safety_notes: "Realistic military violence. Age-rated content.", sort_priority: 2
  },
  {
    title: "Apex Legends", slug: "apex-legends", description_short: "Squad-based battle royale with unique Legend abilities.", developer: "Respawn Entertainment", publisher: "Electronic Arts", franchise: "Apex Legends", multiplayer_type: "battle_royale", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "first_person", genres: ["Battle Royale", "FPS", "Hero Shooter"], tags: ["pvp", "team_based", "battle_royale", "hero_based"], game_modes: ["battle_royale", "ranked", "arena", "custom_match"], core_objective: "Work with your squad to be the last team standing using Legend abilities and gunplay.", win_conditions: "Be the Champion squad. In ranked, gain RP through placement and kills.", fail_conditions: "Entire squad eliminated with no respawn beacons available.", challenge_notes: "Legend-specific challenges are very popular. Ability-only kills, specific weapon challenges, and no-shield runs work well.", safety_notes: "Sci-fi violence, no gore. Generally stream-safe.", sort_priority: 3
  },
  {
    title: "Valorant", slug: "valorant", description_short: "5v5 tactical hero shooter with precise gunplay and agent abilities.", developer: "Riot Games", publisher: "Riot Games", franchise: "Valorant", multiplayer_type: "online_multiplayer", gameplay_pacing: "medium", session_style: "mission_based", challenge_friendly: true, difficulty_style: "competitive", camera_style: "first_person", genres: ["FPS", "Tactical Shooter", "Hero Shooter"], tags: ["pvp", "tactical", "team_based", "competitive", "hero_based"], game_modes: ["ranked", "casual", "custom_match", "deathmatch"], core_objective: "Plant or defuse the spike in round-based tactical gameplay, or eliminate the enemy team.", win_conditions: "Win 13 rounds before the enemy team. In ranked, climb through ranks.", fail_conditions: "Lose the round by being eliminated or failing the spike objective.", challenge_notes: "Agent-specific challenges, knife-only rounds, and economy challenges (eco rounds only) are popular. Sheriff-only is a classic.", safety_notes: "Cartoon-stylized violence. Stream-safe.", sort_priority: 4
  },
  {
    title: "League of Legends", slug: "league-of-legends", description_short: "5v5 MOBA with deep champion roster and competitive ranked play.", developer: "Riot Games", publisher: "Riot Games", franchise: "League of Legends", multiplayer_type: "online_multiplayer", gameplay_pacing: "medium", session_style: "long_sessions", challenge_friendly: true, difficulty_style: "competitive", camera_style: "isometric", genres: ["MOBA", "Strategy"], tags: ["pvp", "team_based", "competitive", "hero_based"], game_modes: ["ranked", "casual", "aram", "custom_match"], core_objective: "Destroy the enemy Nexus by working with your team through lanes and objectives.", win_conditions: "Destroy the enemy Nexus. In ranked, gain LP to climb divisions.", fail_conditions: "Your Nexus is destroyed.", challenge_notes: "Champion-specific challenges, role-swap challenges, and ARAM random builds are great for streams. Off-meta builds create entertaining content.", safety_notes: "Fantasy violence. Some champion designs may be suggestive.", sort_priority: 5
  },
  {
    title: "Minecraft", slug: "minecraft", description_short: "Sandbox survival and creative building game with infinite possibilities.", developer: "Mojang Studios", publisher: "Microsoft", franchise: "Minecraft", multiplayer_type: "mixed", gameplay_pacing: "slow", session_style: "sandbox", challenge_friendly: true, difficulty_style: "casual", camera_style: "first_person", genres: ["Sandbox", "Survival", "Adventure"], tags: ["sandbox", "building", "crafting", "survival", "open_world", "pve"], game_modes: ["survival", "creative", "hardcore", "adventure", "custom_match"], core_objective: "Survive, build, explore, and optionally defeat the Ender Dragon.", win_conditions: "Defeat the Ender Dragon, complete personal goals, or survive indefinitely.", fail_conditions: "Die and lose items (survival), or die permanently (hardcore).", challenge_notes: "Speedrun challenges, hardcore survival, building challenges, and viewer-voted decisions are extremely popular. Minecraft is one of the best games for challenge content.", safety_notes: "Family-friendly. Completely stream-safe.", sort_priority: 6
  },
  {
    title: "GTA V / GTA Online", slug: "gta-v", description_short: "Open-world action-adventure with massive online multiplayer mode.", developer: "Rockstar North", publisher: "Rockstar Games", franchise: "Grand Theft Auto", multiplayer_type: "mixed", gameplay_pacing: "mixed", session_style: "sandbox", challenge_friendly: true, difficulty_style: "casual", camera_style: "third_person", genres: ["Action", "Adventure", "Open World"], tags: ["open_world", "sandbox", "pvp", "pve", "racing"], game_modes: ["campaign", "online_freemode", "races", "heists", "custom_match"], core_objective: "Complete missions, build criminal empire, or free-roam in Los Santos.", win_conditions: "Complete heists, win races, accumulate wealth, or achieve mission objectives.", fail_conditions: "Wasted (killed), busted, or mission failed.", challenge_notes: "Heist challenges, no-kill runs, vehicle-only challenges, and roleplay scenarios are popular. Avoid encouraging real-world illegal behavior.", safety_notes: "Mature content: violence, language, adult themes. Be mindful of stream audience.", sort_priority: 7
  },
  {
    title: "Escape from Tarkov", slug: "escape-from-tarkov", description_short: "Hardcore extraction shooter with realistic combat and loot economy.", developer: "Battlestate Games", publisher: "Battlestate Games", multiplayer_type: "online_multiplayer", gameplay_pacing: "medium", session_style: "short_runs", challenge_friendly: true, difficulty_style: "punishing", camera_style: "first_person", genres: ["FPS", "Extraction Shooter", "Survival"], tags: ["extraction", "pvp", "pve", "tactical", "survival", "permadeath", "hardcore"], game_modes: ["raid", "offline_raid", "arena"], core_objective: "Enter raids, gather loot, complete tasks, and extract alive.", win_conditions: "Successfully extract with valuable loot. Complete trader tasks to progress.", fail_conditions: "Killed in raid — lose all gear brought in (except secured container items).", challenge_notes: "Zero-to-hero runs, pistol-only raids, specific extraction challenges, and quest rushes are great. The permadeath nature makes every challenge high-stakes.", safety_notes: "Realistic military violence and gore. Mature audience.", sort_priority: 8
  },
  {
    title: "Counter-Strike 2", slug: "cs2", description_short: "Classic competitive tactical FPS with precise gunplay.", developer: "Valve", publisher: "Valve", franchise: "Counter-Strike", multiplayer_type: "online_multiplayer", gameplay_pacing: "medium", session_style: "mission_based", challenge_friendly: true, difficulty_style: "competitive", camera_style: "first_person", genres: ["FPS", "Tactical Shooter"], tags: ["pvp", "tactical", "competitive", "team_based"], game_modes: ["ranked", "casual", "deathmatch", "custom_match"], core_objective: "Win rounds by planting/defusing the bomb or eliminating the enemy team.", win_conditions: "Win 13 rounds. In Premier, gain rating through wins.", fail_conditions: "Lose the round by failing objectives or being eliminated.", challenge_notes: "Weapon-specific challenges (Deagle only, knife kills), eco-round only, and clutch challenges are classics.", safety_notes: "Realistic gunplay violence. Stream-safe for gaming audiences.", sort_priority: 9
  },
  {
    title: "Overwatch 2", slug: "overwatch-2", description_short: "5v5 team-based hero shooter with diverse roles and abilities.", developer: "Blizzard Entertainment", publisher: "Blizzard Entertainment", franchise: "Overwatch", multiplayer_type: "online_multiplayer", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "first_person", genres: ["FPS", "Hero Shooter"], tags: ["pvp", "team_based", "competitive", "hero_based"], game_modes: ["ranked", "casual", "arcade", "custom_match"], core_objective: "Work with your team to complete map objectives using hero abilities.", win_conditions: "Complete the map objective or prevent the enemy from doing so.", fail_conditions: "Fail to complete or defend the objective.", challenge_notes: "Hero-specific challenges, role-swap challenges, and mystery heroes are great content. Custom game modes add infinite possibilities.", safety_notes: "Stylized violence, family-friendly. Stream-safe.", sort_priority: 10
  },
  {
    title: "Rust", slug: "rust", description_short: "Multiplayer survival game with base building and PvP.", developer: "Facepunch Studios", publisher: "Facepunch Studios", multiplayer_type: "online_multiplayer", gameplay_pacing: "mixed", session_style: "long_sessions", challenge_friendly: true, difficulty_style: "punishing", camera_style: "first_person", genres: ["Survival", "Sandbox"], tags: ["survival", "building", "crafting", "pvp", "open_world"], game_modes: ["survival", "modded", "custom_match"], core_objective: "Survive, build a base, gather resources, and dominate the server.", win_conditions: "Establish a strong base, raid enemies, control territory.", fail_conditions: "Killed and looted, base raided, or server wiped.", challenge_notes: "Naked-to-raider challenges, solo vs squad, primitive-only wipes, and speedrun base builds are popular.", safety_notes: "Violence, optional nudity (can be censored). Mature audience.", sort_priority: 11
  },
  {
    title: "Elden Ring", slug: "elden-ring", description_short: "Open-world action RPG known for challenging combat.", developer: "FromSoftware", publisher: "Bandai Namco", franchise: "Elden Ring", multiplayer_type: "mixed", gameplay_pacing: "medium", session_style: "long_sessions", challenge_friendly: true, difficulty_style: "punishing", camera_style: "third_person", genres: ["ARPG", "Open World", "Souls-like"], tags: ["boss_fights", "open_world", "pvp", "pve", "permadeath"], game_modes: ["campaign", "co_op", "pvp_invasions"], core_objective: "Explore the Lands Between, defeat demigod bosses, and become Elden Lord.", win_conditions: "Defeat all major bosses and reach an ending.", fail_conditions: "Die to enemies (lose runes, respawn at grace).", challenge_notes: "No-hit runs, level 1 challenges, specific weapon only, and boss rush challenges are extremely popular. Souls games are the king of challenge content.", safety_notes: "Fantasy violence and dark themes. Some horror elements.", sort_priority: 12
  },
  {
    title: "Phasmophobia", slug: "phasmophobia", description_short: "Co-op horror ghost hunting game.", developer: "Kinetic Games", publisher: "Kinetic Games", multiplayer_type: "co_op", gameplay_pacing: "slow", session_style: "short_runs", challenge_friendly: true, difficulty_style: "mixed", camera_style: "first_person", genres: ["Horror", "Co-op"], tags: ["horror", "co_op", "pve", "team_based"], game_modes: ["campaign", "custom_match"], core_objective: "Identify ghost types using paranormal equipment.", win_conditions: "Correctly identify the ghost type and survive.", fail_conditions: "Killed by the ghost during a hunt.", challenge_notes: "Solo challenges, no-equipment runs, speedrun identifications, and viewer-directed decisions are great.", safety_notes: "Horror themes, jump scares. Not suitable for very young audiences.", sort_priority: 13
  },
  {
    title: "Rocket League", slug: "rocket-league", description_short: "Rocket-powered car soccer with competitive ranked play.", developer: "Psyonix", publisher: "Epic Games", franchise: "Rocket League", multiplayer_type: "online_multiplayer", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "third_person", genres: ["Sports", "Racing", "Competitive"], tags: ["competitive", "team_based", "pvp", "physics_chaos"], game_modes: ["ranked", "casual", "rumble", "custom_match"], core_objective: "Score more goals than the opposing team using rocket-powered cars.", win_conditions: "Score more goals within the time limit.", fail_conditions: "Concede more goals than you score.", challenge_notes: "Freestyle-only, no-boost challenges, specific car restrictions, and 1v1 challenges are popular.", safety_notes: "Completely family-friendly. Perfect for all audiences.", sort_priority: 14
  },
  {
    title: "Dead by Daylight", slug: "dead-by-daylight", description_short: "Asymmetric horror game: 4 survivors vs 1 killer.", developer: "Behaviour Interactive", publisher: "Behaviour Interactive", multiplayer_type: "online_multiplayer", gameplay_pacing: "medium", session_style: "short_runs", challenge_friendly: true, difficulty_style: "mixed", camera_style: "mixed", genres: ["Horror", "Survival"], tags: ["horror", "pvp", "team_based", "survival"], game_modes: ["casual", "ranked", "custom_match"], core_objective: "Survivors: repair generators and escape. Killer: sacrifice all survivors.", win_conditions: "Survivors escape through exit gates. Killer hooks all survivors.", fail_conditions: "Survivors sacrificed. Killer fails to catch survivors.", challenge_notes: "No-perk challenges, specific killer challenges, and adept builds are popular stream content.", safety_notes: "Horror violence. Licensed horror characters. Suitable for teen+ audiences.", sort_priority: 15
  },
  {
    title: "Lethal Company", slug: "lethal-company", description_short: "Co-op horror where you scavenge moons for scrap to meet profit quotas.", developer: "Zeekerss", publisher: "Zeekerss", multiplayer_type: "co_op", gameplay_pacing: "medium", session_style: "short_runs", challenge_friendly: true, difficulty_style: "mixed", camera_style: "first_person", genres: ["Horror", "Co-op", "Survival"], tags: ["horror", "co_op", "survival", "team_based"], game_modes: ["campaign"], core_objective: "Explore moons, collect scrap, and meet the Company's profit quota.", win_conditions: "Meet the profit quota by the deadline.", fail_conditions: "All crew members die or fail to meet quota.", challenge_notes: "Solo runs, specific moon challenges, no-flashlight runs, and speed-scavenging are great.", safety_notes: "Horror creature encounters. Stream-safe for gaming audiences.", sort_priority: 16
  },
  {
    title: "Palworld", slug: "palworld", description_short: "Open-world survival crafting with creature collection mechanics.", developer: "Pocketpair", publisher: "Pocketpair", multiplayer_type: "mixed", gameplay_pacing: "medium", session_style: "sandbox", challenge_friendly: true, difficulty_style: "casual", camera_style: "third_person", genres: ["Survival", "Adventure", "Creature Collector"], tags: ["open_world", "survival", "crafting", "building", "pve"], game_modes: ["survival", "co_op"], core_objective: "Capture Pals, build a base, and explore the world.", win_conditions: "Defeat tower bosses, complete the Paldeck, build ultimate base.", fail_conditions: "Die and respawn (lose some items depending on settings).", challenge_notes: "Nuzlocke-style runs, specific Pal only, no-capture challenges, and speedrun boss clears work well.", safety_notes: "Stylized violence. Family-friendly. Stream-safe.", sort_priority: 17
  },
  {
    title: "Helldivers 2", slug: "helldivers-2", description_short: "Co-op third-person shooter fighting for Super Earth.", developer: "Arrowhead Game Studios", publisher: "Sony Interactive", multiplayer_type: "co_op", gameplay_pacing: "fast", session_style: "mission_based", challenge_friendly: true, difficulty_style: "competitive", camera_style: "third_person", genres: ["Shooter", "Co-op", "Action"], tags: ["co_op", "team_based", "pve", "tactical"], game_modes: ["campaign", "helldive", "custom_match"], core_objective: "Complete missions to liberate planets from alien threats.", win_conditions: "Complete all mission objectives and extract.", fail_conditions: "All squad members dead or fail to extract.", challenge_notes: "Highest difficulty challenges, specific stratagem-only runs, and no-death extraction challenges are great content.", safety_notes: "Sci-fi violence. Satirical military themes. Stream-safe.", sort_priority: 18
  },
  {
    title: "The Finals", slug: "the-finals", description_short: "Team-based FPS with full environment destruction.", developer: "Embark Studios", publisher: "Embark Studios", multiplayer_type: "online_multiplayer", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "first_person", genres: ["FPS", "Shooter"], tags: ["pvp", "team_based", "competitive", "physics_chaos"], game_modes: ["ranked", "casual", "custom_match"], core_objective: "Steal and deposit cash boxes while fighting other teams.", win_conditions: "Deposit the most cash or eliminate other teams.", fail_conditions: "Fail to secure cash deposits.", challenge_notes: "Class-specific challenges, destruction-focused challenges, and specific weapon runs are fun.", safety_notes: "Game show violence aesthetic. Stream-safe.", sort_priority: 19
  },
  {
    title: "Stardew Valley", slug: "stardew-valley", description_short: "Farming RPG with crafting, relationships, and exploration.", developer: "ConcernedApe", publisher: "ConcernedApe", multiplayer_type: "mixed", gameplay_pacing: "slow", session_style: "sandbox", challenge_friendly: true, difficulty_style: "casual", camera_style: "top_down", genres: ["Farming Sim", "RPG", "Sandbox"], tags: ["farming", "crafting", "sandbox", "story_rich", "co_op"], game_modes: ["campaign", "co_op"], core_objective: "Build and manage your farm, befriend villagers, explore mines.", win_conditions: "Achieve farm perfection, complete community center, or reach personal goals.", fail_conditions: "Pass out from exhaustion (minor setback). No permanent failure.", challenge_notes: "Speedrun community center, specific crop only, no-mine challenges, and viewer-voted marriage choices are popular.", safety_notes: "Completely family-friendly. Perfect for all audiences.", sort_priority: 20
  },
  {
    title: "Among Us", slug: "among-us", description_short: "Social deduction party game about crewmates and impostors.", developer: "InnerSloth", publisher: "InnerSloth", multiplayer_type: "online_multiplayer", gameplay_pacing: "medium", session_style: "short_runs", challenge_friendly: true, difficulty_style: "casual", camera_style: "top_down", genres: ["Party Game", "Social Deduction"], tags: ["party_game", "team_based", "pvp", "social"], game_modes: ["classic", "hide_and_seek", "custom_match"], core_objective: "Crewmates complete tasks while impostors secretly eliminate them.", win_conditions: "Crewmates: complete all tasks or vote out impostors. Impostors: eliminate enough crewmates.", fail_conditions: "Crewmates fail to identify impostors. Impostors get voted out.", challenge_notes: "Silent impostor, reverse roles, and viewer-directed voting are great for streams.", safety_notes: "Family-friendly. Perfect for all audiences.", sort_priority: 21
  },
  {
    title: "Hades II", slug: "hades-2", description_short: "Roguelike action game with Greek mythology setting.", developer: "Supergiant Games", publisher: "Supergiant Games", franchise: "Hades", multiplayer_type: "single_player", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "competitive", camera_style: "isometric", genres: ["Roguelike", "Action", "ARPG"], tags: ["roguelike", "boss_fights", "pve", "permadeath"], game_modes: ["campaign"], core_objective: "Escape the Underworld through procedurally generated rooms and boss fights.", win_conditions: "Defeat the final boss and complete escape runs.", fail_conditions: "Die during a run (restart from beginning).", challenge_notes: "Specific weapon challenges, no-boon runs, and heat challenges are perfect for streams.", safety_notes: "Fantasy violence. Some suggestive character designs. Stream-safe.", sort_priority: 22
  },
  {
    title: "Baldur's Gate 3", slug: "baldurs-gate-3", description_short: "Epic RPG with deep narrative choices and turn-based combat.", developer: "Larian Studios", publisher: "Larian Studios", franchise: "Baldur's Gate", multiplayer_type: "mixed", gameplay_pacing: "slow", session_style: "long_sessions", challenge_friendly: true, difficulty_style: "mixed", camera_style: "isometric", genres: ["RPG", "Strategy", "Adventure"], tags: ["story_rich", "co_op", "pve", "open_world"], game_modes: ["campaign", "co_op", "honour_mode"], core_objective: "Navigate a rich narrative, make impactful choices, and defeat the Absolute.", win_conditions: "Complete the main quest. In Honour Mode, do it without dying.", fail_conditions: "Party wipe (reload save). In Honour Mode, permadeath.", challenge_notes: "Honour Mode is built-in challenge content. Viewer-voted dialogue choices and pacifist runs are popular.", safety_notes: "Mature themes: violence, romance, dark narrative. Adult audience.", sort_priority: 23
  },
  {
    title: "Fall Guys", slug: "fall-guys", description_short: "Colorful battle royale obstacle course party game.", developer: "Mediatonic", publisher: "Epic Games", franchise: "Fall Guys", multiplayer_type: "battle_royale", gameplay_pacing: "fast", session_style: "short_runs", challenge_friendly: true, difficulty_style: "casual", camera_style: "third_person", genres: ["Party Game", "Battle Royale", "Platformer"], tags: ["party_game", "battle_royale", "physics_chaos", "competitive"], game_modes: ["battle_royale", "squads", "custom_match"], core_objective: "Survive obstacle courses and mini-games to be the last bean standing.", win_conditions: "Win the final round crown.", fail_conditions: "Eliminated in a qualifying round.", challenge_notes: "No-jump challenges, viewer-picked costumes, and win-streak challenges are great for streams.", safety_notes: "Completely family-friendly. Perfect for all audiences.", sort_priority: 24
  },
  {
    title: "Terraria", slug: "terraria", description_short: "2D sandbox adventure with crafting, building, and boss fights.", developer: "Re-Logic", publisher: "Re-Logic", multiplayer_type: "mixed", gameplay_pacing: "medium", session_style: "sandbox", challenge_friendly: true, difficulty_style: "mixed", camera_style: "side_scroller", genres: ["Sandbox", "Adventure", "Survival"], tags: ["sandbox", "building", "crafting", "boss_fights", "pve", "co_op"], game_modes: ["campaign", "expert_mode", "master_mode", "co_op"], core_objective: "Explore, build, and defeat increasingly powerful bosses.", win_conditions: "Defeat Moon Lord and all bosses.", fail_conditions: "Die and respawn (lose coins). In hardcore, permanent death.", challenge_notes: "Class-specific playthroughs, speedruns, and hardcore mode are popular challenge formats.", safety_notes: "Cartoon violence. Family-friendly. Stream-safe.", sort_priority: 25
  }
];

Deno.serve(async (req) => {
  if (req.method !== "POST") return Response.json({ error: "Method not allowed" }, { status: 405 });
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();
  if (user?.role !== "admin") return Response.json({ error: "Forbidden: Admin access required" }, { status: 403 });

  const { force } = await req.json().catch(() => ({}));

  // Check if library already seeded
  const existing = await base44.asServiceRole.entities.GameLibrary.list("-sort_priority", 5);
  if (existing.length > 0 && !force) {
    return Response.json({ message: "Library already seeded", count: existing.length });
  }

  const created = [];
  for (const game of SEED_GAMES) {
    const record = await base44.asServiceRole.entities.GameLibrary.create({
      ...game,
      normalized_title: game.title.toLowerCase(),
      pc_supported: true,
      is_active: true,
    });
    created.push(record.id);
  }

  return Response.json({ message: `Seeded ${created.length} games`, ids: created });
});